### ISSUE TITLE
Add REST APIs to manage worker configuration

### ISSUE THREAD

**Issue by zenmyo** [CyberAgent/patriot-workflow-scheduler#11]

**Comment by tsuda7** [comment]
Solved by https://github.com/CyberAgent/patriot-workflow-scheduler/commit/57fad7c6f616c4c33a37269df4e507cd69a6d903

**Comment by zenmyo** [comment]
Fixed by https://github.com/CyberAgent/patriot-workflow-scheduler/commit/76c18bbd4a543e67f1b6d34ecb86978dafb0638e https://github.com/CyberAgent/patriot-workflow-scheduler/commit/326e5f2cc6f6bbcae64dc8ce274df75fa3a9c536.

New issues will be created for enhancement of the worker api.
